name = "Visualisations"
uuid = "f245dbda-ec9f-4fc8-834d-b0f9c8ddd5e9"
authors = ["Graham Stark"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
